/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedConfig: typeof import('./components/config-drawer/AdvancedConfig.vue')['default']
    AppearanceConfig: typeof import('./components/config-drawer/AppearanceConfig.vue')['default']
    BaseCard: typeof import('./components/cards/BaseCard.vue')['default']
    ConfigPanel: typeof import('./components/config-drawer/ConfigPanel.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePickerPanel: typeof import('element-plus/es')['ElDatePickerPanel']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconButton: typeof import('./components/IconButton.vue')['default']
    IconLayBlank: typeof import('./components/icons/IconLayBlank.vue')['default']
    IconLaySidebar: typeof import('./components/icons/IconLaySidebar.vue')['default']
    IconLaySideMixed: typeof import('./components/icons/IconLaySideMixed.vue')['default']
    IconLaySplit: typeof import('./components/icons/IconLaySplit.vue')['default']
    IconLayTopbar: typeof import('./components/icons/IconLayTopbar.vue')['default']
    IconLayTopSide: typeof import('./components/icons/IconLayTopSide.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LayoutConfig: typeof import('./components/config-drawer/LayoutConfig.vue')['default']
    MenuItem: typeof import('./components/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/search/SearchBox.vue')['default']
    SearchModal: typeof import('./components/search/SearchModal.vue')['default']
    SiteStatusCard: typeof import('./components/cards/SiteStatusCard.vue')['default']
    UserAvatarPopover: typeof import('./components/UserAvatarPopover.vue')['default']
    UserCountCard: typeof import('./components/cards/UserCountCard.vue')['default']
  }
}
